#!/bin/bash

SOFTWARE="/ceph/opt/plink-ng/1.9"
BFILE="../../../../input/genotypes/extract_snps_predgenes/_m"

python ../_h/cluster_samples.py

for TISSUE in caudate dentateGyrus dlpfc hippocampus; do
    mkdir $TISSUE
    ls $BFILE/$TISSUE/*fam | while read -r FILE; do
        GENEID=`basename $FILE .fam`
        Rscript ../_h/select_snps.R \
                --tissue $TISSUE --gname $GENEID --model "rf"
        $SOFTWARE/plink --bfile $BFILE/$TISSUE/$GENEID \
                        --keep samples_keep.tsv \
                        --extract $TISSUE/${GENEID}_snps.txt\
                        --within within_clusters.txt \
                        --fst --out $TISSUE/$GENEID
    done
done
