#!/bin/bash
#$ -cwd
#$ -R y
#$ -l mem_free=18.0G,h_vmem=20G,h_fsize=50G
#$ -N 'subset_genotypes'
#$ -o ./summary.out
#$ -e ./summary.out

echo "**** Job starts ****"
date -Is

echo "**** JHPCE info ****"
echo "User: ${USER}"
echo "Job id: ${JOB_ID}"
echo "Job name: ${JOB_NAME}"
echo "Hostname: ${HOSTNAME}"

module load plink/2.0
module list

echo "**** Subset genotypes ****"

GENOTYPE_DIR='../../../../../input/genotypes/all_samples/_m'

plink2 --bfile $GENOTYPE_DIR/TOPMed_LIBD_AA_EA \
       --keep ../../_m/keepFam.txt \
       --make-bed --out genotypes

echo "**** Job ends ****"
date -Is
