#!/bin/bash
#$ -cwd
#$ -R y
#$ -l h_fsize=50G
#$ -N prepare_gct
#$ -o ./summary.out
#$ -e ./summary.out
#$ -m e -M jade.benjamin@libd.org

FEATURE="gene"
TISSUE="dentateGyrus"

python ../_h/prepare_gct.py --feature $FEATURE --tissue $TISSUE
