#!/bin/bash
#$ -cwd
#$ -R y
#$ -l mem_free=20G,h_vmem=20G
#$ -N upsetplot
#$ -o ./summary.log
#$ -e ./summary.log
#$ -m e -M jade.benjamin@libd.org

echo "**** Job starts ****"
date

echo "**** JHPCE info ****"
echo "User: ${USER}"
echo "Job id: ${JOB_ID}"
echo "Job name: ${JOB_NAME}"
echo "Hostname: ${HOSTNAME}"

## List current modules for reproducibility
module load conda_R
module list

## Job command
echo "**** Generate upset plot ****"
Rscript ../_h/upsetplot.R

echo "**** Job ends ****"
date
