#!/bin/bash
#$ -N pred_jobs.txt
#$ -cwd
#$ -l mem_free=1G,h_vmem=1G,h_fsize=10G,
#$ -q shared.q@compute-0[9]*,shared.q@compute-1*&!*111
#$ -t 1-200
#$ -o ./pred_jobs.txt_err_out
#$ -e ./pred_jobs.txt_err_out

echo "**** Job starts ****"
date
module load conda_R/4.0
module load plink/2.0
perl /users/shan/script/job_batch.pl --jfile pred_jobs.txt --nrun 1 --n $SGE_TASK_ID

echo "**** Job ends ****"
date
