#!/bin/bash

## Make feature list for parallel run
parallel -k echo ::: genes transcripts exons junctions > feature.list

## Prep files
cat feature.list | parallel "mkdir {}; python ../_h/prep_files.py --feature {}"

## Preform mashr
cat feature.list | parallel "Rscript ../_h/mashr_script.R --feature {}"

## Clean directory
rm feature.list
