#!/bin/bash
#$ -cwd
#$ -R y
#$ -l mem_free=10G,h_vmem=10G
#$ -N correlation_plot
#$ -o ./summary.log
#$ -e ./summary.log
#$ -m e -M jade.benjamin@libd.org

echo "**** Job starts ****"
date

echo "**** JHPCE info ****"
echo "User: ${USER}"
echo "Job id: ${JOB_ID}"
echo "Job name: ${JOB_NAME}"
echo "Hostname: ${HOSTNAME}"

## List current modules for reproducibility
module load R/3.6.1
module list

## Job command
echo "**** Generate correlation heatmap ****"
Rscript ../_h/corrplot_sharing.R

echo "**** Job ends ****"
date
