#!/bin/bash

## Make feature list for parallel run
parallel -k echo ::: Caudate DLPFC Hippocampus 'Dentate Gyrus' > tissue.list

## Run analysis
cat tissue.list | parallel "python ../_h/variation_pca.py --tissue {}"

## Clean directory
rm tissue.list
