#!/bin/bash

# SOFTWARE="/ceph/opt/PGDSpider_2.1.1.5"

# for TISSUE in caudate dentateGyrus dlpfc hippocampus; do
#     echo $TISSUE
#     mkdir $TISSUE
#     ls ../../_m/$TISSUE/*ped | while read -r PED; do
#         GENEID=`basename $PED .ped`
#         java -Xmx1G -Xms512m -jar $SOFTWARE/PGDSpider2-cli.jar \
#              -inputfile $PED -inputformat PED \
#              -outputfile $TISSUE/$GENEID.arp -outputformat ARLEQUIN \
#              -spid ../_h/PED_to_ARLEQUIN.spid
#     done
# done

ls ../_h/*convert.sh | parallel bash {}
