#!/bin/bash
#$ -cwd
#$ -R y
#$ -l h_fsize=50G
#$ -N residualize_expression
#$ -o ./summary.out
#$ -e ./summary.out

echo "**** Job starts ****"
date -Is

echo "**** JHPCE info ****"
echo "User: ${USER}"
echo "Job id: ${JOB_ID}"
echo "Job name: ${JOB_NAME}"
echo "Hostname: ${HOSTNAME}"

module load gcc/9.1.0
module load pandoc
module load R

module list

echo "**** Generate residualization ****"

FEATURE="genes"

Rscript ../_h/generate_residualized_expression.R --feature $FEATURE

echo "**** Job ends ****"
date -Is
